#!/bin/sh
set -e

if [ "$1" = "remove" ] || [ "$1" = "purge" ]; then
    echo "\e[1m[*](1) http://imcurvin.imcurvin: bad\e[0m"
fi

if [ "$1" = "purge" ]; then
    rm -rf /usr/share/imcurvin
fi

#DEBHELPER#

exit 0