#!/bin/bash
set -e

if [ "$1" = "configure" ]; then
    cat > /usr/bin/imcurvin << 'EOF'
#!/bin/bash
export PYTHONPATH="$PYTHONPATH:/usr/share/imcurvin"
cd /usr/share/imcurvin/Imcurvin || exit 1
exec ./imcurvin.sh "$@"
EOF
    chmod +x /usr/bin/imcurvin    
    echo -e "[i] ImCurvin 1.3.0 \033[1msuccessfully integrated.\033[0m"
    echo -e "[i] Type \033[1m'imcurvin -h'\033[0m to display the basic options list."
    echo -e "[i] Please ensure \033[1mtarget environment supports multi-statement execution (Stacked Queries).\033[0m"
fi

#DEBHELPER#

exit 0