name: Build Debian Package
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4      
      - name: Build Package
        run: |
          mkdir -p build-root/DEBIAN
          mkdir -p build-root/usr/bin
          mkdir -p build-root/usr/share/imcurvin
          mkdir -p build-root/usr/share/applications
          mkdir -p build-root/usr/share/icons/hicolor/512x512/apps
          
          cp DEBIAN/control build-root/DEBIAN/
          echo "" >> build-root/DEBIAN/control
          
          cat << 'EOF' > build-root/usr/bin/imcurvin
          #!/bin/bash
          cd /usr/share/imcurvin/Imcurvin || exit 1
          exec bash ./imcurvin.sh "$@"
          EOF
          
          cat << 'EOF' > build-root/usr/share/applications/imcurvin.desktop
          [Desktop Entry]
          Version=1.3.0
          Type=Application
          Name=imcurvin
          Comment=Advanced multi-vector vulnerability exploitation and perimeter reconnaissance framework featuring synchronized dual-vector parallel processing and high-concurrency layer bypass matrices.
          Exec=imcurvin
          Icon=imcurvin.jpg
          Terminal=true
          Categories=Network;Security;DataRecovery;
          Keywords=scan;scanner;network;security;imcurvin;
          EOF
          
          rsync -av \
            --exclude='build-root' \
            --exclude='DEBIAN' \
            --exclude='debian' \
            --exclude='.git' \
            --exclude='.github' \
            --exclude='ScreenShots' \
            --exclude='LICENSE' \
            --exclude='*.md' \
            --exclude='*.log' \
            ./ build-root/usr/share/imcurvin/
          
          if [ -f "ri.jpg" ]; then
            echo "ri.jpg avaible"
            cp ri.jpg build-root/usr/share/icons/hicolor/512x512/apps/imcurvin.jpg
          fi
          
          chmod 755 build-root/DEBIAN
          chmod 755 build-root/usr/bin/imcurvin
          chmod 644 build-root/usr/share/applications/imcurvin.desktop
          chmod -R 755 build-root/usr/share/imcurvin
          chmod +x debian/rules 2>/dev/null || true
          
          dpkg-deb --build build-root ImCurvin.deb
          
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: debian-package
          path: ImCurvin.deb
          